apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: dgraph-alpha-public
  path: set-alpha-service-nodeport.yml